version: '3.9'

services:
  postgres:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ~/src/main/resources/db-files:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dimuth
      - POSTGRES_USER=dimuth
      - POSTGRES_DB=dimuth
  credit-card-expense-tracker:
    image: registry.hub.docker.com/dimuthnc/credit-card-expense-tracker
    ports:
      - "8085:8085"
    environment:
      - POSTGRES_PASSWORD=dimuth
      - POSTGRES_USERNAME=dimuth
      - DATA_SOURCE_URL=jdbc:postgresql://db:5432/dimuth