name: Check branch name

on:
  push:
    branches:
      - "*"

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          branch_name=${{ github.ref_name }}
          if [[ ! $branch_name =~ ^(feature/|release/|hotfix/).* ]]; then
            echo "Error: Branch name must start with feature/, release/, or hotfix/"
            exit 1
          fi
